### ISSUE TITLE
Big play Button issue in Firefox

### ISSUE THREAD

**Issue by timokuehne** [hola/videojs5-hola-skin#2]
![big-play](https://cloud.githubusercontent.com/assets/11676348/17707997/2c73a270-63e3-11e6-9f61-3ec0a9a48af0.png)

**Comment by norlin** [comment]
Thank you for the bug! Will check it soon.

**Comment by timokuehne** [comment]
We solved the following issues for you:
1. SVG pause icon stroke issue
2. big play button issue on firefox
3. big replay icon issue at the end of the video

You can download the code from this example page if you want. Have a nice day.

http://dev.videolyser.de/github/index.html
