### ISSUE TITLE
Duplicate Button's when using youtube or vimeo 

### ISSUE THREAD

**Issue by bm2ilabs** [hola/videojs5-hola-skin#3]
Hello , first of all thanks for the skin 
this issue doesn't appear when using normal videos but it does when using videos from youtube or vimeo , 

[![Untitled-2.png](https://s12.postimg.org/ejee1071p/Untitled_2.png)](https://postimg.org/image/kx3h49bxl/)

**Comment by norlin** [comment]
Thank you for the issue!
Could you please make an example? (e.g., via jsbin or other similar service)

**Comment by bm2ilabs** [comment]
it seems working in JSbin i guess the issue is in my part 
https://jsbin.com/yopureposa
