### ISSUE TITLE
Subtitles button not showing correctly

### ISSUE THREAD

**Issue by ColorsCL** [hola/videojs5-hola-skin#4]
Hello. Thanks for the skin, I don't really like the new VideoJS 5 layout and this is more like the previous version (VideoJS 4).

![Image of error](http://puu.sh/sOdQH/de110ca62c.png)

When you add subtitles or custom buttons (via plugins) the new icons/buttons don't show correctly.
Also, is there a way to move this buttons next to the fullscreen one?

Thanks in advance.

**Comment by skyh** [comment]
Hi, CC button is fixed in [v0.0.5-43](/hola/videojs5-hola-skin/releases/tag/v0.0.5-43)
